
package com.b2winc.query.item;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-04T19:06:01.395-03:00
 * Generated source version: 3.0.0
 * 
 */
public final class GetBasicItemInfoWS_GetBasicItemInfoWSSoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://br/com/b2winc/service", "GetBasicItemInfoWSService");
    private static URL wsdlURL = GetBasicItemInfoWSService.WSDL_LOCATION;
    
    public GetBasicItemInfoWS_GetBasicItemInfoWSSoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetBasicItemInfoWSService ss = new GetBasicItemInfoWSService(wsdlURL, SERVICE_NAME);
        GetBasicItemInfoWS port = ss.getGetBasicItemInfoWSSoapPort();  
        
        {
        System.out.println("Invoking getBasicItemInfo...");
        
        GetBasicItemInfoRequest request = new GetBasicItemInfoRequest();  
        request.setItemId(new Long(7929890));
        
        com.b2winc.query.item.GetBasicItemInfo _getBasicItemInfo_parameters = new GetBasicItemInfo();
        _getBasicItemInfo_parameters.setGetBasicItemInfoRequest(request);
        com.b2winc.query.item.GetBasicItemInfoResponse _getBasicItemInfo__return = port.getBasicItemInfo(_getBasicItemInfo_parameters);
        System.out.println("getBasicItemInfo.result=" + _getBasicItemInfo__return);
        System.out.println("NCM "+_getBasicItemInfo__return.getGetBasicItemInfoResponse().getItem().getSkuList().getSku().get(0).getNBMInfo().getNBM());

        }

        System.exit(0);
    }
    
    
    public String getNBM(int id){
    	
    	GetBasicItemInfoWSService ss = new GetBasicItemInfoWSService(wsdlURL, SERVICE_NAME);
        GetBasicItemInfoWS port = ss.getGetBasicItemInfoWSSoapPort();
        GetBasicItemInfoRequest request = new GetBasicItemInfoRequest();  
        request.setItemId(new Long(id));
        
        com.b2winc.query.item.GetBasicItemInfo _getBasicItemInfo_parameters = new GetBasicItemInfo();
        _getBasicItemInfo_parameters.setGetBasicItemInfoRequest(request);
        com.b2winc.query.item.GetBasicItemInfoResponse _getBasicItemInfo__return = port.getBasicItemInfo(_getBasicItemInfo_parameters);
        return _getBasicItemInfo__return.getGetBasicItemInfoResponse().getItem().getSkuList().getSku().get(0).getNBMInfo().getNBM();
    	
    }
    
    private static String getItemMistoService(int id){
    	
    	GetBasicItemInfoWSService ss = new GetBasicItemInfoWSService(wsdlURL, SERVICE_NAME);
        GetBasicItemInfoWS port = ss.getGetBasicItemInfoWSSoapPort();
        GetBasicItemInfoRequest request = new GetBasicItemInfoRequest();  
        request.setItemId(new Long(id));
        
        com.b2winc.query.item.GetBasicItemInfo _getBasicItemInfo_parameters = new GetBasicItemInfo();
        _getBasicItemInfo_parameters.setGetBasicItemInfoRequest(request);
        com.b2winc.query.item.GetBasicItemInfoResponse _getBasicItemInfo__return = port.getBasicItemInfo(_getBasicItemInfo_parameters);
        return _getBasicItemInfo__return.getGetBasicItemInfoResponse().getItem().getSkuList().getSku().get(0).getSkuPropertyList().getSkuProperty().get(0).getSkuPropertyValue();
    	
    }
    
    public static boolean getItemMisto(int id){
    	if(getItemMistoService(id).equalsIgnoreCase("1")) 
    		return true;
    	else
    		return false;
    }
    
}
