package com.b2winc.query.item;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-04T19:06:01.471-03:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://br/com/b2winc/service", name = "GetBasicItemInfoWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetBasicItemInfoWS {

    @WebResult(name = "getBasicItemInfoResponse", targetNamespace = "http://br/com/b2winc/service", partName = "parameters")
    @WebMethod
    public GetBasicItemInfoResponse getBasicItemInfo(
        @WebParam(partName = "parameters", name = "getBasicItemInfo", targetNamespace = "http://br/com/b2winc/service")
        GetBasicItemInfo parameters
    );
}
