
package com.b2winc.query.item;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-04T19:06:01.449-03:00
 * Generated source version: 3.0.0
 * 
 */
public final class GetBasicItemInfoWS_GetBasicItemInfoWSPt_Client {

    private static final QName SERVICE_NAME = new QName("http://br/com/b2winc/service", "getBasicItemInfo");

    private GetBasicItemInfoWS_GetBasicItemInfoWSPt_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GetBasicItemInfo_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetBasicItemInfo_Service ss = new GetBasicItemInfo_Service(wsdlURL, SERVICE_NAME);
        GetBasicItemInfoWS port = ss.getGetBasicItemInfoWSPt();  
        
        {
        System.out.println("Invoking getBasicItemInfo...");
        com.b2winc.query.item.GetBasicItemInfo _getBasicItemInfo_parameters = null;
        com.b2winc.query.item.GetBasicItemInfoResponse _getBasicItemInfo__return = port.getBasicItemInfo(_getBasicItemInfo_parameters);
        System.out.println("getBasicItemInfo.result=" + _getBasicItemInfo__return);


        }

        System.exit(0);
    }

}
