package com.b2wdigital.tools;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-07-10T11:27:36.380-03:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://com/b2w/tools/ws", name = "ToolsWs")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ToolsWs {

    @WebResult(name = "getProductIdsResponse", targetNamespace = "http://com/b2w/tools/ws", partName = "parameters")
    @WebMethod
    public GetProductIdsResponse getProductIds(
        @WebParam(partName = "parameters", name = "getProductIds", targetNamespace = "http://com/b2w/tools/ws")
        GetProductIds parameters
    );

    @WebResult(name = "getArtistInfoResponse", targetNamespace = "http://com/b2w/tools/ws", partName = "parameters")
    @WebMethod
    public GetArtistInfoResponse getArtistInfo(
        @WebParam(partName = "parameters", name = "getArtistInfo", targetNamespace = "http://com/b2w/tools/ws")
        GetArtistInfo parameters
    );

    @WebResult(name = "getProductionItemInfoResponse", targetNamespace = "http://com/b2w/tools/ws", partName = "parameters")
    @WebMethod
    public GetProductionItemInfoResponse getProductionItemInfo(
        @WebParam(partName = "parameters", name = "getProductionItemInfo", targetNamespace = "http://com/b2w/tools/ws")
        GetProductionItemInfo parameters
    );
}
