package com.b2winc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-04T18:24:06.881-03:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://com/b2winc/product/pricing/webservice", name = "GetItemPriceList")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetItemPriceList {

    @WebResult(name = "getItemPriceListResponse", targetNamespace = "http://com/b2winc/product/pricing/webservice", partName = "parameters")
    @WebMethod
    public GetItemPriceListResponse getItemPriceList(
        @WebParam(partName = "parameters", name = "getItemPriceList", targetNamespace = "http://com/b2winc/product/pricing/webservice")
        GetItemPriceList_Type parameters
    );
}
